import csv
from pathlib import Path
from sqlalchemy import Table, Column, String, MetaData
from sqlalchemy.ext.asyncio import AsyncEngine
from .base import BaseProfile

metadata = MetaData()

lfa1 = Table("LFA1", metadata,
    Column("MANDT", String(255)),
    Column("LIFNR", String(255)),
    Column("LAND1", String(255)),
    Column("NAME1", String(255)),
    Column("NAME2", String(255)),
    Column("NAME3", String(255)),
    Column("NAME4", String(255)),
    Column("ORT01", String(255)),
    Column("ORT02", String(255)),
    Column("PFACH", String(255)),
    Column("PSTL2", String(255)),
    Column("PSTLZ", String(255)),
    Column("REGIO", String(255)),
    Column("SORTL", String(255)),
    Column("STRAS", String(255)),
    Column("ADRNR", String(255)),
    Column("MCOD1", String(255)),
    Column("MCOD2", String(255)),
    Column("MCOD3", String(255)),
    Column("ANRED", String(255)),
    Column("BAHNS", String(255)),
    Column("BBBNR", String(255)),
    Column("BBSNR", String(255)),
    Column("BEGRU", String(255)),
    Column("BRSCH", String(255)),
    Column("BUBKZ", String(255)),
    Column("DATLT", String(255)),
    Column("DTAMS", String(255)),
    Column("DTAWS", String(255)),
    Column("ERDAT", String(255)),
    Column("ERNAM", String(255)),
    Column("ESRNR", String(255)),
    Column("KONZS", String(255)),
    Column("KTOKK", String(255)),
    Column("KUNNR", String(255)),
    Column("LNRZA", String(255)),
    Column("LOEVM", String(255)),
    Column("SPERR", String(255)),
    Column("SPERM", String(255)),
    Column("SPRAS", String(255)),
    Column("STCD1", String(255)),
    Column("STCD2", String(255)),
    Column("STKZA", String(255)),
    Column("STKZU", String(255)),
    Column("TELBX", String(255)),
    Column("TELF1", String(255)),
    Column("TELF2", String(255)),
    Column("TELFX", String(255)),
    Column("TELTX", String(255)),
    Column("TELX1", String(255)),
    Column("XCPDK", String(255)),
    Column("XZEMP", String(255)),
    Column("VBUND", String(255)),
    Column("FISKN", String(255)),
    Column("STCEG", String(255)),
    Column("STKZN", String(255)),
    Column("SPERQ", String(255)),
    Column("GBORT", String(255)),
    Column("GBDAT", String(255)),
    Column("SEXKZ", String(255)),
    Column("KRAUS", String(255)),
    Column("REVDB", String(255)),
    Column("QSSYS", String(255)),
    Column("KTOCK", String(255)),
    Column("PFORT", String(255)),
    Column("WERKS", String(255)),
    Column("LTSNA", String(255)),
    Column("WERKR", String(255)),
    Column("PLKAL", String(255)),
    Column("DUEFL", String(255)),
    Column("TXJCD", String(255)),
    Column("SPERZ", String(255)),
    Column("SCACD", String(255)),
    Column("SFRGR", String(255)),
    Column("LZONE", String(255)),
    Column("XLFZA", String(255)),
    Column("DLGRP", String(255)),
    Column("STCD3", String(255)),
    Column("STCD4", String(255)),
    Column("STCD5", String(255)),
    Column("PROFS", String(255)),
    Column("EMNFR", String(255)),
    Column("LFURL", String(255)),
    Column("CONFS", String(255)),
    Column("UPDAT", String(255)),
    Column("UPTIM", String(255)),
    Column("NODEL", String(255)),
    Column("PODKZB", String(255)),
)

lfb1 = Table("LFB1", metadata,
    Column("MANDT", String(255)),
    Column("LIFNR", String(255)),
    Column("BUKRS", String(255)),
    Column("PERNR", String(255)),
    Column("ALTKN", String(255)),
    Column("BEGRU", String(255)),
    Column("ZUAWA", String(255)),
    Column("AKONT", String(255)),
    Column("ALTKT", String(255)),
    Column("ALTKN2", String(255)),
    Column("ZTERM", String(255)),
    Column("WAERS", String(255)),
    Column("FDGRP", String(255)),
    Column("REPRF", String(255)),
    Column("TOGRP", String(255)),
    Column("LNRZE", String(255)),
    Column("LNRZB", String(255)),
    Column("ZINDT", String(255)),
    Column("ZINRT", String(255)),
    Column("DATLZ", String(255)),
    Column("ALTKZ", String(255)),
    Column("MINDK", String(255)),
    Column("INTAD", String(255)),
    Column("KVERM", String(255)),
    Column("BUSAB", String(255)),
    Column("UBBZG", String(255)),
    Column("EXPKK", String(255)),
    Column("ABSBE", String(255)),
    Column("ZFBDT", String(255)),
    Column("SKFOR", String(255)),
    Column("SKNTO", String(255)),
    Column("MANDT_OVERRIDE", String(255)),
)

lfbk = Table("LFBK", metadata,
    Column("MANDT", String(255)),
    Column("LIFNR", String(255)),
    Column("BANKS", String(255)),
    Column("BANKL", String(255)),
    Column("BANKN", String(255)),
    Column("BKONT", String(255)),
    Column("BVTYP", String(255)),
    Column("XEZER", String(255)),
    Column("BANKA", String(255)),
    Column("PROVZ", String(255)),
    Column("STRAS", String(255)),
    Column("ORT01", String(255)),
    Column("SWIFT", String(255)),
    Column("IBAN", String(255)),
    Column("KOINH", String(255)),
    Column("KOVON", String(255)),
    Column("KOBIS", String(255)),
)

lfas = Table("LFAS", metadata,
    Column("MANDT", String(255)),
    Column("LIFNR", String(255)),
    Column("EKORG", String(255)),
    Column("SPERM", String(255)),
    Column("LOEVM", String(255)),
    Column("VENSL", String(255)),
    Column("BSTAE", String(255)),
)

lfm1 = Table("LFM1", metadata,
    Column("MANDT", String(255)),
    Column("LIFNR", String(255)),
    Column("EKORG", String(255)),
    Column("WAERS", String(255)),
    Column("LIEFR", String(255)),
    Column("MINBW", String(255)),
    Column("KZABS", String(255)),
    Column("KZAUT", String(255)),
    Column("KZBESN", String(255)),
    Column("MEPRF", String(255)),
    Column("INCO1", String(255)),
    Column("INCO2", String(255)),
    Column("WEBRE", String(255)),
    Column("KZWBK", String(255)),
    Column("BOAUF", String(255)),
    Column("BOKRE", String(255)),
    Column("BOSPE", String(255)),
    Column("BOSTA", String(255)),
    Column("BOSPE2", String(255)),
    Column("UMSAE", String(255)),
)

lfm2 = Table("LFM2", metadata,
    Column("MANDT", String(255)),
    Column("LIFNR", String(255)),
    Column("EKORG", String(255)),
    Column("WERKS", String(255)),
    Column("SPERM", String(255)),
    Column("LOEVM", String(255)),
    Column("PLIFZ", String(255)),
    Column("MNGLG", String(255)),
    Column("MNGKO", String(255)),
    Column("MNGZE", String(255)),
    Column("UEBTO", String(255)),
    Column("UNTTO", String(255)),
    Column("UGBTO", String(255)),
)

lfb5 = Table("LFB5", metadata,
    Column("MANDT", String(255)),
    Column("LIFNR", String(255)),
    Column("BUKRS", String(255)),
    Column("MABER", String(255)),
    Column("MAHNS", String(255)),
    Column("MANDT2", String(255)),
)

lfbw = Table("LFBW", metadata,
    Column("MANDT", String(255)),
    Column("LIFNR", String(255)),
    Column("BUKRS", String(255)),
    Column("WITHT", String(255)),
    Column("WT_WITHCD", String(255)),
    Column("WT_EXPT", String(255)),
    Column("QSREC", String(255)),
    Column("WITHT2", String(255)),
)

kna1 = Table("KNA1", metadata,
    Column("MANDT", String(255)),
    Column("KUNNR", String(255)),
    Column("LAND1", String(255)),
    Column("NAME1", String(255)),
    Column("NAME2", String(255)),
    Column("NAME3", String(255)),
    Column("NAME4", String(255)),
    Column("ORT01", String(255)),
    Column("ORT02", String(255)),
    Column("PSTLZ", String(255)),
    Column("REGIO", String(255)),
    Column("SORTL", String(255)),
    Column("STRAS", String(255)),
    Column("TELF1", String(255)),
    Column("TELF2", String(255)),
    Column("TELFX", String(255)),
    Column("TELTX", String(255)),
    Column("XCPDK", String(255)),
    Column("STCD1", String(255)),
    Column("STCD2", String(255)),
    Column("STKZU", String(255)),
    Column("ERDAT", String(255)),
    Column("ERNAM", String(255)),
    Column("KTOKD", String(255)),
    Column("SPRAS", String(255)),
    Column("ANRED", String(255)),
    Column("MCOD1", String(255)),
    Column("MCOD2", String(255)),
    Column("MCOD3", String(255)),
    Column("LOEVM", String(255)),
    Column("SPERR", String(255)),
)

knb1 = Table("KNB1", metadata,
    Column("MANDT", String(255)),
    Column("KUNNR", String(255)),
    Column("BUKRS", String(255)),
    Column("AKONT", String(255)),
    Column("ZTERM", String(255)),
    Column("WAERS", String(255)),
    Column("ZUAWA", String(255)),
    Column("BEGRU", String(255)),
    Column("ALTKN", String(255)),
    Column("REPRF", String(255)),
)

knvv = Table("KNVV", metadata,
    Column("MANDT", String(255)),
    Column("KUNNR", String(255)),
    Column("VKORG", String(255)),
    Column("VTWEG", String(255)),
    Column("SPART", String(255)),
    Column("BZIRK", String(255)),
    Column("VKBUR", String(255)),
    Column("KDGRP", String(255)),
    Column("WAERS", String(255)),
    Column("ZTERM", String(255)),
    Column("INCO1", String(255)),
    Column("INCO2", String(255)),
    Column("KVGR1", String(255)),
    Column("KVGR2", String(255)),
    Column("KVGR3", String(255)),
    Column("KVGR4", String(255)),
    Column("KVGR5", String(255)),
)

knbk = Table("KNBK", metadata,
    Column("MANDT", String(255)),
    Column("KUNNR", String(255)),
    Column("BANKS", String(255)),
    Column("BANKL", String(255)),
    Column("BANKN", String(255)),
    Column("BKONT", String(255)),
    Column("BVTYP", String(255)),
    Column("XEZER", String(255)),
    Column("BANKA", String(255)),
    Column("SWIFT", String(255)),
    Column("IBAN", String(255)),
)

mara = Table("MARA", metadata,
    Column("MANDT", String(255)),
    Column("MATNR", String(255)),
    Column("ERSDA", String(255)),
    Column("ERNAM", String(255)),
    Column("LAEDA", String(255)),
    Column("AENAM", String(255)),
    Column("MTART", String(255)),
    Column("MBRSH", String(255)),
    Column("MATKL", String(255)),
    Column("MEINS", String(255)),
    Column("BSTME", String(255)),
    Column("ZEINR", String(255)),
    Column("ZEIVR", String(255)),
    Column("ZEIFO", String(255)),
    Column("AESZN", String(255)),
    Column("BLANZ", String(255)),
    Column("FERTH", String(255)),
    Column("FORMT", String(255)),
    Column("NORMT", String(255)),
    Column("LABOR", String(255)),
    Column("EKWSL", String(255)),
    Column("BRGEW", String(255)),
    Column("GEWEI", String(255)),
    Column("NTGEW", String(255)),
    Column("VOLUM", String(255)),
    Column("VOLEH", String(255)),
    Column("BEHVO", String(255)),
    Column("RAUBE", String(255)),
    Column("TEMPB", String(255)),
    Column("DISST", String(255)),
    Column("TRAGR", String(255)),
    Column("STOFF", String(255)),
    Column("SPART", String(255)),
    Column("VHART", String(255)),
    Column("FUELG", String(255)),
    Column("IPRKZ", String(255)),
    Column("RDPRF", String(255)),
    Column("MHDRZ", String(255)),
    Column("MHDLP", String(255)),
    Column("MHDLF", String(255)),
    Column("BWVOR", String(255)),
    Column("BWSCL", String(255)),
    Column("SAISO", String(255)),
    Column("ETIAR", String(255)),
    Column("ETIFO", String(255)),
    Column("ENTAR", String(255)),
    Column("EAN11", String(255)),
    Column("NUMTP", String(255)),
    Column("LAENG", String(255)),
    Column("BREIT", String(255)),
    Column("HOEHE", String(255)),
    Column("MEABM", String(255)),
    Column("PRDHA", String(255)),
    Column("CADKZ", String(255)),
    Column("ERGEW", String(255)),
    Column("ERVOLM", String(255)),
    Column("WERKS", String(255)),
    Column("LMEINS", String(255)),
    Column("BRGEW2", String(255)),
    Column("GEWEI2", String(255)),
)

marc = Table("MARC", metadata,
    Column("MANDT", String(255)),
    Column("MATNR", String(255)),
    Column("WERKS", String(255)),
    Column("PSTAT", String(255)),
    Column("LVORM", String(255)),
    Column("BWTTY", String(255)),
    Column("XCHAR", String(255)),
    Column("MMSTA", String(255)),
    Column("MMSTD", String(255)),
    Column("MAABC", String(255)),
    Column("KZKRI", String(255)),
    Column("EKGRP", String(255)),
    Column("DISMM", String(255)),
    Column("DISPO", String(255)),
    Column("DISLS", String(255)),
    Column("BERID", String(255)),
    Column("BSTMI", String(255)),
    Column("MINBE", String(255)),
    Column("EISBE", String(255)),
    Column("MABST", String(255)),
    Column("STRGR", String(255)),
    Column("LGPRO", String(255)),
    Column("LGFSB", String(255)),
    Column("HERKL", String(255)),
    Column("INSMK", String(255)),
    Column("SSQSS", String(255)),
    Column("MTVFP", String(255)),
    Column("KZAUS", String(255)),
    Column("AUSDT", String(255)),
    Column("NFMAT", String(255)),
    Column("MFLHN", String(255)),
    Column("KZBED", String(255)),
    Column("LGPBE", String(255)),
    Column("LGOBE", String(255)),
    Column("INSMK2", String(255)),
)

makt = Table("MAKT", metadata,
    Column("MANDT", String(255)),
    Column("MATNR", String(255)),
    Column("SPRAS", String(255)),
    Column("MAKTX", String(255)),
    Column("MAKTG", String(255)),
)

ska1 = Table("SKA1", metadata,
    Column("MANDT", String(255)),
    Column("KTOPL", String(255)),
    Column("SAKNR", String(255)),
    Column("BILKT", String(255)),
    Column("ERDAT", String(255)),
    Column("ERNAM", String(255)),
    Column("GVTYP", String(255)),
    Column("KTOKS", String(255)),
    Column("MUSTR", String(255)),
    Column("VBUND", String(255)),
    Column("XBILK", String(255)),
    Column("XLOEV", String(255)),
    Column("XSPEA", String(255)),
    Column("XSPEB", String(255)),
    Column("XUMSA", String(255)),
)

skat = Table("SKAT", metadata,
    Column("MANDT", String(255)),
    Column("SPRAS", String(255)),
    Column("KTOPL", String(255)),
    Column("SAKNR", String(255)),
    Column("TXT20", String(255)),
    Column("TXT50", String(255)),
)

csks = Table("CSKS", metadata,
    Column("MANDT", String(255)),
    Column("KOSTL", String(255)),
    Column("DATBI", String(255)),
    Column("DATAB", String(255)),
    Column("BKLAS", String(255)),
    Column("BUKRS", String(255)),
    Column("GSBER", String(255)),
    Column("KOKRS", String(255)),
    Column("KOSTLV", String(255)),
    Column("KHINR", String(255)),
    Column("KOSAR", String(255)),
    Column("VERAK", String(255)),
    Column("VERAK2", String(255)),
    Column("KTEXT", String(255)),
    Column("LTEXT", String(255)),
    Column("FUNC_AREA", String(255)),
)

ekko = Table("EKKO", metadata,
    Column("MANDT", String(255)),
    Column("EBELN", String(255)),
    Column("BUKRS", String(255)),
    Column("BSART", String(255)),
    Column("LIFNR", String(255)),
    Column("EKORG", String(255)),
    Column("EKGRP", String(255)),
    Column("WAERS", String(255)),
    Column("WKURS", String(255)),
    Column("KUFIX", String(255)),
    Column("BEDAT", String(255)),
    Column("KDATB", String(255)),
    Column("KDATE", String(255)),
    Column("KDATV", String(255)),
    Column("ABGRU", String(255)),
    Column("AUTLF", String(255)),
    Column("WEAKT", String(255)),
    Column("MEMORY", String(255)),
    Column("KZABS", String(255)),
    Column("RLWRT", String(255)),
    Column("ZTERM", String(255)),
    Column("ZBD1T", String(255)),
    Column("ZBD2T", String(255)),
    Column("ZBD3T", String(255)),
    Column("ZBD1P", String(255)),
    Column("ZBD2P", String(255)),
    Column("MWSKZ", String(255)),
    Column("IHREZ", String(255)),
    Column("VERKF", String(255)),
    Column("EXNUM", String(255)),
    Column("UNSEZ", String(255)),
    Column("INCO1", String(255)),
    Column("INCO2", String(255)),
    Column("KONNR", String(255)),
    Column("KTPNR", String(255)),
    Column("ABTYP", String(255)),
    Column("WGLIF", String(255)),
    Column("KNUMV", String(255)),
)

ekpo = Table("EKPO", metadata,
    Column("MANDT", String(255)),
    Column("EBELN", String(255)),
    Column("EBELP", String(255)),
    Column("MATNR", String(255)),
    Column("WERKS", String(255)),
    Column("LGORT", String(255)),
    Column("MATKL", String(255)),
    Column("INFNR", String(255)),
    Column("IDNLF", String(255)),
    Column("KTMNG", String(255)),
    Column("MENGE", String(255)),
    Column("MEINS", String(255)),
    Column("BPRME", String(255)),
    Column("BPUMZ", String(255)),
    Column("BPUMN", String(255)),
    Column("NETPR", String(255)),
    Column("PEINH", String(255)),
    Column("NETWR", String(255)),
    Column("BRTWR", String(255)),
    Column("BUGSZ", String(255)),
    Column("RETPO", String(255)),
    Column("WEPOS", String(255)),
    Column("WEUNB", String(255)),
    Column("REPOS", String(255)),
    Column("MWSKZ", String(255)),
    Column("ADRNR", String(255)),
    Column("PACKNO", String(255)),
    Column("FPLNR", String(255)),
    Column("BELNR", String(255)),
    Column("LOEKZ", String(255)),
    Column("BANFN", String(255)),
    Column("BNFPO", String(255)),
    Column("EBELN2", String(255)),
    Column("EBELP2", String(255)),
)

_ALL_TABLES = [
    lfa1, lfb1, lfbk, lfas, lfm1, lfm2, lfb5, lfbw,
    kna1, knb1, knvv, knbk,
    mara, marc, makt,
    ska1, skat, csks,
    ekko, ekpo,
]

_CSV_DIR = Path(__file__).parent.parent.parent / "data" / "seed"

_TABLE_ORDER = [
    ("LFA1", lfa1), ("LFB1", lfb1), ("LFBK", lfbk), ("LFAS", lfas),
    ("LFM1", lfm1), ("LFM2", lfm2), ("LFB5", lfb5), ("LFBW", lfbw),
    ("KNA1", kna1), ("KNB1", knb1), ("KNVV", knvv), ("KNBK", knbk),
    ("MARA", mara), ("MARC", marc), ("MAKT", makt),
    ("SKA1", ska1), ("SKAT", skat), ("CSKS", csks),
    ("EKKO", ekko), ("EKPO", ekpo),
]


class SapEccProfile(BaseProfile):

    @property
    def profile_id(self) -> str:
        return "sap_ecc"

    @property
    def system_name(self) -> str:
        return "ECC-1"

    @property
    def system_type(self) -> str:
        return "SAP ECC"

    @property
    def version(self) -> str:
        return "6.0 EHP8"

    @property
    def description(self) -> str:
        return "SAP ECC 6.0 EHP8 — legacy system with 15+ years of accumulated data"

    async def create_tables(self, engine: AsyncEngine) -> None:
        async with engine.begin() as conn:
            await conn.run_sync(metadata.create_all)

    async def drop_tables(self, engine: AsyncEngine) -> None:
        async with engine.begin() as conn:
            await conn.run_sync(metadata.drop_all)

    async def seed_data(self, engine: AsyncEngine) -> None:
        async with engine.begin() as conn:
            for table_name, table_obj in _TABLE_ORDER:
                csv_path = _CSV_DIR / f"{table_name}.csv"
                with open(csv_path, newline="", encoding="utf-8") as f:
                    rows = [
                        {k: (v if v != "" else None) for k, v in row.items()}
                        for row in csv.DictReader(f)
                    ]
                for i in range(0, len(rows), 500):
                    await conn.execute(table_obj.insert(), rows[i : i + 500])

    def get_tables(self) -> list[dict]:
        return [
            {"name": "LFA1", "domain": "Vendor Master", "record_count": 2000, "primary_keys": ["MANDT", "LIFNR"]},
            {"name": "LFB1", "domain": "Vendor Master", "record_count": 3000, "primary_keys": ["MANDT", "LIFNR", "BUKRS"]},
            {"name": "LFBK", "domain": "Vendor Master", "record_count": 2000, "primary_keys": ["MANDT", "LIFNR", "BANKS", "BANKL", "BANKN"]},
            {"name": "LFAS", "domain": "Vendor Master", "record_count": 2500, "primary_keys": ["MANDT", "LIFNR", "EKORG"]},
            {"name": "LFM1", "domain": "Vendor Master", "record_count": 2500, "primary_keys": ["MANDT", "LIFNR", "EKORG"]},
            {"name": "LFM2", "domain": "Vendor Master", "record_count": 3000, "primary_keys": ["MANDT", "LIFNR", "EKORG", "WERKS"]},
            {"name": "LFB5", "domain": "Vendor Master", "record_count": 1500, "primary_keys": ["MANDT", "LIFNR", "BUKRS", "MABER"]},
            {"name": "LFBW", "domain": "Vendor Master", "record_count": 1000, "primary_keys": ["MANDT", "LIFNR", "BUKRS", "WITHT"]},
            {"name": "KNA1", "domain": "Customer Master", "record_count": 2000, "primary_keys": ["MANDT", "KUNNR"]},
            {"name": "KNB1", "domain": "Customer Master", "record_count": 2500, "primary_keys": ["MANDT", "KUNNR", "BUKRS"]},
            {"name": "KNVV", "domain": "Customer Master", "record_count": 3000, "primary_keys": ["MANDT", "KUNNR", "VKORG", "VTWEG", "SPART"]},
            {"name": "KNBK", "domain": "Customer Master", "record_count": 2000, "primary_keys": ["MANDT", "KUNNR", "BANKS", "BANKL"]},
            {"name": "MARA", "domain": "Material Master", "record_count": 2000, "primary_keys": ["MANDT", "MATNR"]},
            {"name": "MARC", "domain": "Material Master", "record_count": 5000, "primary_keys": ["MANDT", "MATNR", "WERKS"]},
            {"name": "MAKT", "domain": "Material Master", "record_count": 3000, "primary_keys": ["MANDT", "MATNR", "SPRAS"]},
            {"name": "SKA1", "domain": "Finance", "record_count": 400, "primary_keys": ["MANDT", "KTOPL", "SAKNR"]},
            {"name": "SKAT", "domain": "Finance", "record_count": 500, "primary_keys": ["MANDT", "SPRAS", "KTOPL", "SAKNR"]},
            {"name": "CSKS", "domain": "Finance", "record_count": 300, "primary_keys": ["MANDT", "KOSTL", "DATBI"]},
            {"name": "EKKO", "domain": "Purchasing", "record_count": 5000, "primary_keys": ["MANDT", "EBELN"]},
            {"name": "EKPO", "domain": "Purchasing", "record_count": 15000, "primary_keys": ["MANDT", "EBELN", "EBELP"]},
        ]

    def get_schema(self, table_name: str) -> dict:
        _descriptions = {
            "MANDT": "Client",
            "LIFNR": "Vendor Account Number",
            "LAND1": "Country Key",
            "NAME1": "Name 1",
            "NAME2": "Name 2",
            "NAME3": "Name 3",
            "NAME4": "Name 4",
            "ORT01": "City",
            "ORT02": "District",
            "PSTLZ": "Postal Code",
            "REGIO": "Region (State/Province)",
            "STRAS": "Street Address",
            "LOEVM": "Central Deletion Flag",
            "SPERR": "Central Posting Block",
            "SPERM": "Purchasing Block",
            "SPRAS": "Language Key",
            "ERDAT": "Date Record Created",
            "ERNAM": "Name of Person Who Created Record",
            "BUKRS": "Company Code",
            "EKORG": "Purchasing Organization",
            "WERKS": "Plant",
            "KUNNR": "Customer Account Number",
            "MATNR": "Material Number",
            "EBELN": "Purchasing Document Number",
            "EBELP": "Item Number of Purchasing Document",
            "KTOKK": "Vendor Account Group",
            "WAERS": "Currency Key",
            "ZTERM": "Terms of Payment Key",
            "INCO1": "Incoterms (Part 1)",
            "INCO2": "Incoterms (Part 2)",
            "AKONT": "Reconciliation Account",
            "BRSCH": "Industry",
            "SORTL": "Sort Field",
            "STCD1": "Tax Number 1",
            "STCEG": "VAT Registration Number",
            "TELF1": "First Telephone Number",
            "KTOPL": "Chart of Accounts",
            "SAKNR": "G/L Account Number",
            "KOSTL": "Cost Center",
            "DATBI": "Valid To Date",
            "DATAB": "Valid From Date",
            "MAKTX": "Material Description",
            "MTART": "Material Type",
            "MEINS": "Base Unit of Measure",
            "MENGE": "Purchase Order Quantity",
            "NETPR": "Net Price",
            "NETWR": "Net Order Value",
        }

        table_obj_map = {
            "LFA1": lfa1, "LFB1": lfb1, "LFBK": lfbk, "LFAS": lfas,
            "LFM1": lfm1, "LFM2": lfm2, "LFB5": lfb5, "LFBW": lfbw,
            "KNA1": kna1, "KNB1": knb1, "KNVV": knvv, "KNBK": knbk,
            "MARA": mara, "MARC": marc, "MAKT": makt,
            "SKA1": ska1, "SKAT": skat, "CSKS": csks,
            "EKKO": ekko, "EKPO": ekpo,
        }
        tbl = table_obj_map.get(table_name)
        if tbl is None:
            return {"table_name": table_name, "columns": []}

        columns = []
        for col in tbl.columns:
            columns.append({
                "name": col.name,
                "type": "String(255)",
                "nullable": True,
                "description": _descriptions.get(col.name, col.name),
                "sample_values": [],
            })
        return {"table_name": table_name, "columns": columns}

    def get_relationships(self, table_name: str) -> list[dict]:
        _rels = {
            "LFB1": [{"from_table": "LFB1", "from_column": "LIFNR", "to_table": "LFA1", "to_column": "LIFNR"}],
            "LFBK": [{"from_table": "LFBK", "from_column": "LIFNR", "to_table": "LFA1", "to_column": "LIFNR"}],
            "LFAS": [{"from_table": "LFAS", "from_column": "LIFNR", "to_table": "LFA1", "to_column": "LIFNR"}],
            "LFM1": [{"from_table": "LFM1", "from_column": "LIFNR", "to_table": "LFA1", "to_column": "LIFNR"}],
            "LFM2": [{"from_table": "LFM2", "from_column": "LIFNR", "to_table": "LFM1", "to_column": "LIFNR"}],
            "LFB5": [{"from_table": "LFB5", "from_column": "LIFNR", "to_table": "LFB1", "to_column": "LIFNR"}],
            "LFBW": [{"from_table": "LFBW", "from_column": "LIFNR", "to_table": "LFB1", "to_column": "LIFNR"}],
            "KNB1": [{"from_table": "KNB1", "from_column": "KUNNR", "to_table": "KNA1", "to_column": "KUNNR"}],
            "KNVV": [{"from_table": "KNVV", "from_column": "KUNNR", "to_table": "KNA1", "to_column": "KUNNR"}],
            "KNBK": [{"from_table": "KNBK", "from_column": "KUNNR", "to_table": "KNA1", "to_column": "KUNNR"}],
            "MARC": [{"from_table": "MARC", "from_column": "MATNR", "to_table": "MARA", "to_column": "MATNR"}],
            "MAKT": [{"from_table": "MAKT", "from_column": "MATNR", "to_table": "MARA", "to_column": "MATNR"}],
            "EKKO": [{"from_table": "EKKO", "from_column": "LIFNR", "to_table": "LFA1", "to_column": "LIFNR"}],
            "EKPO": [
                {"from_table": "EKPO", "from_column": "EBELN", "to_table": "EKKO", "to_column": "EBELN"},
                {"from_table": "EKPO", "from_column": "MATNR", "to_table": "MARA", "to_column": "MATNR"},
            ],
        }
        return _rels.get(table_name, [])
